### ISSUE TITLE
Questions related to the experimental environment, training duration, and the Camelyon16 dataset in the paper.

### ISSUE THREAD

**Issue by blz822** [ls1rius/WSI_FiVE#11]
Hi authors, 

I have read your paper "Generalizable Whole Slide Image Classification with Fine-Grained Visual-Semantic Interaction" and have some questions.

I'm curious about the details of the experimental environment for your experiments. Besides the 4 NVIDIA-A800 GPUs you mentioned, have you also tried training the model on other GPU models, such as the 3090? If yes, what were the differences in performance and training time compared to using the NVIDIA-A800?

Also, how long did the entire training process take? Were there any significant differences in training time among different datasets or experiments?

Regarding the Camelyon16 dataset, were Pathology Reports available for this dataset? If so, how were they utilized in the research?

Looking forward to your response, and thank you very much in advance.

**Comment by ls1rius** [comment]
If you conduct end-to-end training, the GPU resource requirements are relatively large since the image encoder is trained simultaneously. Based on our preset parameters, end-to-end training occupies approximately 67G of GPU memory, which necessitates NVIDIA-A800 GPU. However, for pre-trained pth, the GPU requirements are significantly lower, with a 3090 GPU (occupying around 17G) being sufficient, and the training speed is faster compared to end-to-end.

Since WSIs information is redundant, training speed can be improved by reducing the MAXN value of the samples. However, this adjustment may lead to slight fluctuations in performance. A detailed analysis of this trade-off is provided in Section 4.6.2 of the paper.

In terms of performance, end-to-end training offers better generalization and higher performance for subtype tasks, whereas pre-trained models perform poorly on these tasks. However, for binary classification tasks, the performance difference between the two approaches is minimal.

Regarding training time, end-to-end training generally takes about two days, while using a pre-trained model reduces the time to less than one day. If training resources are sufficient, we recommend end2end training.

As for the Camelyon16 dataset, we have not found pathology reports associated with it and thus did not utilize them in our research.

**Comment by blz822** [comment]
> If you conduct end-to-end training, the GPU resource requirements are relatively large since the image encoder is trained simultaneously. Based on our preset parameters, end-to-end training occupies approximately 67G of GPU memory, which necessitates NVIDIA-A800 GPU. However, for pre-trained pth, the GPU requirements are significantly lower, with a 3090 GPU (occupying around 17G) being sufficient, and the training speed is faster compared to end-to-end.
> 
> Since WSIs information is redundant, training speed can be improved by reducing the MAXN value of the samples. However, this adjustment may lead to slight fluctuations in performance. A detailed analysis of this trade-off is provided in Section 4.6.2 of the paper.
> 
> In terms of performance, end-to-end training offers better generalization and higher performance for subtype tasks, whereas pre-trained models perform poorly on these tasks. However, for binary classification tasks, the performance difference between the two approaches is minimal.
> 
> Regarding training time, end-to-end training generally takes about two days, while using a pre-trained model reduces the time to less than one day. If training resources are sufficient, we recommend end2end training.
> 
> As for the Camelyon16 dataset, we have not found pathology reports associated with it and thus did not utilize them in our research.

OK, thank you for your patient response.
